.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TELNETLOGGER" "8" "November 2016" "" ""
.
.SH "NAME"
\fBtelnetlogger\fR \- Tiny telnet honeypot
.
.SH "SYNOPSIS"
telnetlogger \fIoptions\fR
.
.SH "DESCRIPTION"
\fBtelnetlogger\fR is a small daemon that accepts incomiong Telnet connections and logs the username/password attempts\. Specifically, it is designed to log attempts from the Mirai IoT worm\.
.
.P
There are three output formats: just the passwords, just the IP addresses, or a CSV output containing both\.
.
.P
The way I run this is on a Raspberry Pi with the following parameters:
.
.IP "" 4
.
.nf

telnetlogger \-c telnet\.csv \-p null \-i null \-l 2323
.
.fi
.
.IP "" 0
.
.P
I then use the firewall to redirect incoming port 23 to my network to the Raspberry Pi on port 2323\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-c <filename>\fR: An output file in CSV format containing the time, IP address, username, and password for each attempt\. A filename of \fB\-\fR means \fIstdout\fR, a filename of \fBnull\fR means no output\.
.
.IP "\(bu" 4
\fB\-i <filename>\fR: An output file for the IPv4/IPv6 addresses logged by the daemon\. A filename of \fB\-\fR means \fIstdout\fR, a filename of \fBnull\fR means no output\. If no filename given, the passwords will be printed to the command\-line\.
.
.IP "\(bu" 4
\fB\-p <filename>\fR: An output file for the passwords logged by the daemon\. A filename of \fB\-\fR means \fIstdout\fR, a filename of \fBnull\fR means no output\. If no filename given, the passwords will be printed to the command\-line\.
.
.IP "\(bu" 4
\fB\-l <port>\fR: A port number to listen on\. Often, people will setup the service to listen on a high\-numbered port, such as 2323, then use firewall rules to redirect the Telnet port 23 to this high\-numbered port\. If not specified, by default port 23 will be used\. This may require root priveleges to run on low\-numbered ports\.
.
.IP "" 0
.
.SH "COMPATIBILITY"
The tool runs on Windows and Linux, but should run on most other systems as well\.
.
.SH "AUTHORS"
This tool was written by Robert Graham\. The source code is available at https://github\.com/robertdavidgraham/telnetlogger\.
